### PR TITLE
Move to Kubewarden official SDK

### PR DESCRIPTION
**Pull request by flavio**
Consume the official SDK of Kubewarden. This reduces the code duplication.

It also makes the final policy smaller, because the dependency against the official Kubernetes APIs is dropped.

**Blocked:** waiting for changes to the official Go SDK to happen

### CODE REVIEW

**Comment by flavio** [comment]
Waiting for https://github.com/kubewarden/policy-sdk-go/pull/64 to be merged, and a new version of the SDK to be tagged

**Comment by flavio** [comment]
Ready to be reviewed

**Comment by flavio** [comment]
Note, some tests will keep failing until https://github.com/kubewarden/github-actions/pull/105 is merged and a new version of our actions is tagged.

**Review by viccuad — APPROVED** [review]
LGTM

**Review by fabriziosestito — APPROVED** [review]

**Comment by flavio** [comment]
All green, we can merge it! :partying_face:

**Pull request merged**
